export const START_LOADING_CATEGORIES = 'START_LOADING_CATEGORIES';
export const END_LOADING_CATEGORIES = 'END_LOADING_CATEGORIES';
export const SET_CATEGORIES = 'SET_CATEGORIES';

export const START_LOADING_ATTRACTIONS = 'START_LOADING_ATTRACTIONS';
export const END_LOADING_ATTRACTIONS = 'END_LOADING_ATTRACTIONS';

export const ADD_FAVORITE_ATTRACTION = 'ADD_FAVORITE_ATTRACTION';
